name: Build and tag

on:
  push:
    branches:
      - main # Default release branch
    tags:
      - "!*"

jobs:
  build:
    name: build and tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: get-version
        id: get_version
        uses: bbonkr/get-version-action@v1.0.3
        with:
          project: src/AppleTv.Movie.Price.Tracker.App/AppleTv.Movie.Price.Tracker.App.csproj

      - uses: bbonkr/git-tag-check-action@v1.0.9
        id: git_tag_check
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tag: "v${{ steps.get_version.outputs.version }}"

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        if: ${{ steps.git_tag_check.outputs.tag == '' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.get_version.outputs.version }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

